name: LeagueManager
version: 1.2.4
author: Neeonn
depend:
  - LuckPerms
  - WorldGuard
load: POSTWORLD
main: io.github.divinerealms.LeagueManager
commands:
  leaguemanager:
    description: Base command.
    aliases: [lm]
  timer:
    description: Timer command.
    aliases: [tm]
  result:
    description: Result command.
    aliases: [rs]